const questions = [
  {
    id: 'q_00', // 画像のファイル名
    answer: 'パトカー',
    english: 'police car',
    spanish: 'pcoche de policía',
    check: 'パトカー',
  },
  {
    id: 'q_01',
    answer: 'バス',
    english: 'bus',
    spanish: 'autobús',
    check: 'バス',
  },
  {
    id: 'q_02',
    answer: 'タクシー',
    english: 'cab',
    spanish: '',
    check: 'タクシー',
  },
  {
    id: 'q_03',
    answer: 'しょうぼうしゃ',
    english: 'fire-engine',
    spanish: 'camión de bomberos',
    check: '消防車',
  },
  {
    id: 'q_04',
    answer: 'ゆうびんしゃ',
    english: 'mail truck',
    spanish: 'camión de bomberos',
    check: '郵便車',
  },
  {
    id: 'q_05',
    answer: 'きゅうきゅうしゃ',
    english: 'ambulance',
    spanish: 'camión de bomberos',
    check: '救急車',
  },
  {
    id: 'q_06',
    answer: 'ショベルカー',
    english: 'excavator',
    spanish: '',
    check: 'ショベルカー',
  },
  {
    id: 'q_07',
    answer: 'ゴミしゅうしゅうしゃ',
    english: 'garbage truck',
    spanish: '',
    check: 'ゴミ収集車',
  },
  {
    id: 'q_08',
    answer: 'キャリアカー',
    english: 'carrier car',
    spanish: '',
    check: 'キャリアカー',
  },
  {
    id: 'q_09',
    answer: 'クレーンしゃ',
    english: 'mobile crane',
    spanish: '',
    check: 'クレーン車',
  },
  {
    id: 'q_10',
    answer: 'タンクローリー',
    english: 'tanker truck',
    spanish: '',
    check: 'タンクローリー',
  },
  {
    id: 'q_11',
    answer: 'ダンプカー',
    english: 'dump truck',
    spanish: '',
    check: 'ダンプカー',
  },
  {
    id: 'q_12',
    answer: 'ちゅうけいしゃ',
    english: 'stellite truck',
    spanish: '',
    check: '中継車',
  },
  {
    id: 'q_13',
    answer: 'はしごしゃ',
    english: 'ladder truck',
    spanish: '',
    check: 'はしご車',
  },
  {
    id: 'q_14',
    answer: 'トラック',
    english: 'truck',
    spanish: '',
    check: 'トラック',
  },
  {
    id: 'q_15',
    answer: 'フォークリフト',
    english: 'forklift',
    spanish: '',
    check: 'フォークリフト',
  },
  {
    id: 'q_16',
    answer: 'ブルドーザー',
    english: 'bulldozer',
    spanish: '',
    check: 'ブルドーザー',
  },
  {
    id: 'q_17',
    answer: 'ホイールローダー',
    english: 'wheel loader',
    spanish: '',
    check: 'ホイールローダー',
  },
  {
    id: 'q_18',
    answer: 'リムジン',
    english: 'limousine',
    spanish: '',
    check: 'リムジン',
  },
  {
    id: 'q_19',
    answer: 'ロードローラー',
    english: 'road roller',
    spanish: '',
    check: 'ロードローラー',
  },
  {
    id: 'q_20',
    answer: 'ミキサーしゃ',
    english: 'mixer truck',
    spanish: '',
    check: 'ミキサー車',
  },
  // {
  //   id: 'q_21',
  //   answer: 'こうしょさぎょうしゃ',
  //   english: 'aerial work platform',
  //   spanish: '',
  //   check: '高所作業車',
  // },
  {
    id: 'q_22',
    answer: 'さんすいしゃ',
    english: 'sprinkler truck',
    spanish: '',
    check: '散水車',
  },
  // {
  //   id: 'q_23',
  //   answer: 'じんいんゆそうしゃ',
  //   english: 'personnel transport bus',
  //   spanish: '',
  //   check: '人員輸送車',
  // },
  {
    id: 'q_24',
    answer: 'どうろパトロールカー',
    english: 'road patrol car',
    spanish: '',
    check: '道路パトロールカー',
  },
  {
    id: 'q_25',
    answer: 'しろバイ',
    english: 'motorcycle police',
    spanish: '',
    check: '白バイ',
  },
  {
    id: 'q_26',
    answer: 'れいとうしゃ',
    english: 'refrigerator car',
    spanish: '',
    check: '冷凍車',
  },
  {
    id: 'q_27',
    answer: 'ゆうびんバイク',
    english: 'mail bike',
    spanish: '',
    check: '郵便バイク',
  },
  {
    id: 'q_28',
    answer: 'ききゅう',
    english: 'balloon',
    spanish: '',
    check: '気球',
  },
  {
    id: 'q_29',
    answer: 'ひこうき',
    english: 'airplane',
    spanish: '',
    check: '飛行機',
  },
  {
    id: 'q_30',
    answer: 'UFO',
    english: 'UFO',
    spanish: '',
    check: 'UFO',
  },
  {
    id: 'q_31',
    answer: 'りんご',
    english: 'apple',
    spanish: '',
    check: 'りんご',
  },
  {
    id: 'q_32',
    answer: 'バナナ',
    english: 'banana',
    spanish: '',
    check: 'バナナ',
  },
  {
    id: 'q_33',
    answer: 'キャベツ',
    english: 'cabbage',
    spanish: '',
    check: 'キャベツ',
  },
  {
    id: 'q_34',
    answer: 'にんじん',
    english: 'carrot',
    spanish: '',
    check: '人参',
  },
  {
    id: 'q_35',
    answer: 'チェリー',
    english: 'cherry',
    spanish: '',
    check: 'チェリー',
  },
  {
    id: 'q_36',
    answer: 'とうもろこし',
    english: 'corn',
    spanish: '',
    check: 'とうもろこし',
  },
  {
    id: 'q_37',
    answer: 'なす',
    english: 'eggplant',
    spanish: '',
    check: 'なす',
  },
  {
    id: 'q_38',
    answer: 'ぶどう',
    english: 'grape',
    spanish: '',
    check: 'ぶどう',
  },
  {
    id: 'q_39',
    answer: 'ネギ',
    english: 'green onion',
    spanish: '',
    check: 'ネギ',
  },
  {
    id: 'q_40',
    answer: 'ピーマン',
    english: 'green pepper',
    spanish: '',
    check: 'ピーマン',
  },
  {
    id: 'q_41',
    answer: 'レモン',
    english: 'lemon',
    spanish: '',
    check: 'レモン',
  },
  {
    id: 'q_42',
    answer: 'メロン',
    english: 'melon',
    spanish: '',
    check: 'メロン',
  },
  {
    id: 'q_43',
    answer: 'オクラ',
    english: 'okra',
    spanish: '',
    check: 'オクラ',
  },
  {
    id: 'q_44',
    answer: 'たまねぎ',
    english: 'onion',
    spanish: '',
    check: '玉ねぎ',
  },
  {
    id: 'q_45',
    answer: 'モモ',
    english: 'peach',
    spanish: '',
    check: 'もも',
  },
  {
    id: 'q_46',
    answer: 'ようなし',
    english: 'pear',
    spanish: '',
    check: '洋梨',
  },
  {
    id: 'q_47',
    answer: 'じゃがいも',
    english: 'potatoes',
    spanish: '',
    check: 'じゃがいも',
  },
  {
    id: 'q_48',
    answer: 'かぼちゃ',
    english: 'pumpkin',
    spanish: '',
    check: 'かぼちゃ',
  },
  {
    id: 'q_49',
    answer: 'しいたけ',
    english: 'shiitake mushrooms',
    spanish: '',
    check: 'しいたけ',
  },
  {
    id: 'q_50',
    answer: 'いちご',
    english: 'strawberry',
    spanish: '',
    check: 'いちご',
  },
  {
    id: 'q_51',
    answer: 'トマト',
    english: 'tomato',
    spanish: '',
    check: 'トマト',
  },
  {
    id: 'q_52',
    answer: 'すいか',
    english: 'watermelon',
    spanish: '',
    check: 'スイカ',
  },
  {
    id: 'q_53',
    answer: 'ヘリコプター',
    english: 'helicopter',
    spanish: '',
    check: 'ヘリコプター',
  },
  {
    id: 'q_54',
    answer: 'ひこうせん',
    english: 'airship',
    spanish: '',
    check: '飛行船',
  },
  {
    id: 'q_55',
    answer: 'ダンプトラック',
    english: 'heavy dump truck',
    spanish: '',
    check: 'ダンプトラック',
  },
  {
    id: 'q_56',
    answer: 'じてんしゃ',
    english: 'bicycle',
    spanish: '',
    check: '自転車',
  },
  {
    id: 'q_57',
    answer: 'しょくぱん',
    english: 'white bread',
    spanish: '',
    check: '食パン',
  },
  {
    id: 'q_58',
    answer: 'おにぎり',
    english: 'rice ball',
    spanish: '',
    check: 'おにぎり',
  },
  {
    id: 'q_59',
    answer: 'スペースシャトル',
    english: 'space shuttle',
    spanish: '',
    check: 'スペースシャトル',
  },
];

export default questions;
